### ISSUE TITLE
org.openbmc.control.BmcFlash service don't work in openbmc 2.9

### ISSUE THREAD

**Issue by vicye** [openbmc/openbmc#3763]
Dear All
It seems openbmc 2.9 don't support python2.
Therefore, original  obmc-flash-bmc_git.bb recipe needs to be modified to support python3.
The following is my bbappend file for  obmc-flash-bmc_git.bb

DEPENDS_remove_class-target = " python"
DEPENDS_append_class-target = " python3"
RDEPENDS_${PN}_remove += "\
        python-dbus \
        python-compression \
        python-shell \
        python-pygobject \
        python-subprocess \
        python-io \
        "
RDEPENDS_${PN} += "\
        ${PYTHON_PN}-dbus \
        ${PYTHON_PN}-compression \
        ${PYTHON_PN}-shell \
        ${PYTHON_PN}-pygobject \
        ${PYTHON_PN}-io \
        
however, it still doesn't work on openbmc 2.9 target machine.
when I run the python script bmc_update.py  alone, some error occurs.

root@******:/usr/lib# python /usr/sbin/bmc_update.py
Traceback (most recent call last):
  File "/usr/sbin/bmc_update.py", line 5, in <module>
    import gobject
ModuleNotFoundError: No module named 'gobject'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/bmc_update.py", line 7, in <module>
    from gi.repository import GObject as gobject
  File "/usr/lib/python3.8/site-packages/gi/importer.py", line 132, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GObject, introspection typelib not found

Does anyone know how to solve the issue?

**Comment by williamspatrick** [comment]
Yocto removed support for Python2. This code hasn’t been used on any mainline machine in years (like 3 or more) and I don’t think anyone intends to update it to Python3. There are C++ applications that have replaced this code for managing code update on the BMC. Can you convert your system to use those?

Do you have the ability to upstream your machine?  That would make it more obvious if we end up breaking something else.
