### ISSUE TITLE
openpower-pnor-code-mgmt fails to compile with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#3137]
openpower-pnor-code-mgmt@207469f901a9cd3ea791e9a7bec4d8c697ac479c fails to compile against OpenSSL 1.1.0, which is shipped in Ubuntu Bionic (18.04)

```
In file included from utest.cpp:6:0:                                                                                                                                                               
../image_verify.hpp:29:45: error: '::EVP_MD_CTX_destroy' has not been declared                                                                                                                     
     std::unique_ptr<EVP_MD_CTX, decltype(&::EVP_MD_CTX_destroy)>;                               
                                             ^~~~~~~~~~~~~~~~~~                                  
../image_verify.hpp:29:45: note: suggested alternative: 'EVP_MD_CTX_reset'                       
     std::unique_ptr<EVP_MD_CTX, decltype(&::EVP_MD_CTX_destroy)>;                               
                                             ^~~~~~~~~~~~~~~~~~                                  
                                             EVP_MD_CTX_reset                                    
../image_verify.hpp:29:64: error: template argument 2 is invalid                                 
     std::unique_ptr<EVP_MD_CTX, decltype(&::EVP_MD_CTX_destroy)>; 
```

See also #3135 and #3136 .

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/12546> image_verify: Add support for OpenSSL 1.1.0
Resolves  #3137 openpower-pnor-code-mgmt fails to compile with OpenSSL 1.1.0
