### PR TITLE
qemu-native: fix build on Ubuntu 15.10

### PR DESCRIPTION
**Pull request by amboar**
Build of qemu-native on Ubuntu 15.10 fails on configure step.
The reason for this is that system dbus version is higher than
oe dbus version and system pulseaudio libraries require newer dbus.

It causes configure to break with a lot of errors similar to this:
  libpulsecommon-6.0.so: undefined reference to dbus_watch_get_enabled@LIBDBUS_1_3

Fixed by building qemu-native with the system dbus on Ubuntu 15.10

Note: This is a workaround. It must be removed when oe dbus is upgraded
to the version >= system dbus version (1.10.0 at the moment).

[YOCTO #8553]

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Signed-off-by: Ed Bartosh <ed.bartosh@linux.intel.com>

### CODE REVIEW

**Comment by shenki** [comment]
@jenkins-openbmc add to whitelist
